apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse-ui

spec:
  replicas: 1

  selector:
    matchLabels:
      app: synapse-ui

  template:
    metadata:
      labels:
        app: synapse-ui

    spec:
      containers:
        - name: synapse-ui
          image: aariskazi/synapse-ui:latest
          imagePullPolicy: Never

          env:
            - name: VITE_GOOGLE_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: synapse
                  key: VITE_GOOGLE_CLIENT_ID

          ports:
            - containerPort: 3000